### ISSUE TITLE
Missing tags and/or releases

### ISSUE THREAD

**Issue by gizmecano** [cyrealtype/Alice#2]
Due to miss of [tags](https://github.com/cyrealtype/Alice/tags) or [releases](https://github.com/cyrealtype/Alice/releases), the current status of this  project seems somewhat unclear.

If we refer to the log, the last major version (2.000) was published on December 15, 2016.

https://github.com/cyrealtype/Alice/blob/90df8a8d76798026cef675c7e6b2eaa61cff0095/FONTLOG.txt#L40-L41

But it seems this the project has since been completely revised: with the overhaul of the `.otf` and `.ttf` files and the addition of the variables `.woff2` file commited in 90df8a8d76798026cef675c7e6b2eaa61cff0095, the effective tag should have probably been incremented?

Could you consider using tags and/or releases to explicit the situation?

**Comment by alexeiva** [comment]
Yes. Latest release is [here](https://github.com/cyrealtype/Alice/releases/tag/v2.002)

**Comment by gizmecano** [comment]
> Yes. Latest release is [here](https://github.com/cyrealtype/Alice/releases/tag/v2.002)

Thank you very much for this clarification.
