### ISSUE TITLE
Consider type.today's Cyrillic review

### ISSUE THREAD

**Issue by thlinard** [cyrealtype/Alice#3]
https://type.today/en/journal/transitional#Alice

**Comment by alexeiva** [comment]
Updated glyphs `ЏџӋ`
before:
<img width="1105" alt="Screenshot 2021-11-05 at 13 04 49" src="https://user-images.githubusercontent.com/16634089/140493862-2ebee246-2705-47de-8ab2-76203f38003c.png">


after:
<img width="1129" alt="Screenshot 2021-11-05 at 13 05 45" src="https://user-images.githubusercontent.com/16634089/140493880-a6148d4f-45c7-4c66-a385-838780bb1dd1.png">
